#!/usr/bin/env bash
# -*- coding: utf-8 -*-

#pre_install() {
#  :
#}

post_install() {
  local files=('/usr/share/pacman/keyrings/pubring.gpg' '/usr/share/pacman/keyrings/trustdb.gpg')
  mkdir -p /etc/pacman.d/gnupg
  for file in "${files[@]}"; do
    cp -f "$file" /etc/pacman.d/gnupg/
    rm -f "$file"
  done
}

#pre_upgrade() {
#  :
#}

post_upgrade() {
  post_install
}

#pre_remove() {
#  :
#}

#post_remove() {
#  :
#}
